# DO NOT EDIT THIS FILE

.PHONY: test check

build:
	dune build

code:
	-dune build
	code .
	! dune build --watch

utop:
	OCAMLRUNPARAM=b dune utop 

test:
	OCAMLRUNPARAM=b dune exec tests/tests.exe

game:
	OCAMLRUNPARAM=b dune exec bin/game.exe

bisect: bisect-clean
	-dune exec --instrument-with bisect_ppx --force tests/tests.exe
	bisect-ppx-report html

bisect-clean:
	rm -rf _coverage bisect*.coverage

check:
	@bash check.sh

finalcheck:
	@bash check.sh final

zip:
	rm -f ngrams.zip
	zip -r ngrams.zip . -x@exclude.lst

clean:
	dune clean
	rm -f ngrams.zip

doc:
	dune build @doc

opendoc: doc
	@bash opendoc.sh