lib: [
  "_build/install/default/lib/Builder/META"
  "_build/install/default/lib/Builder/builder.a"
  "_build/install/default/lib/Builder/builder.cma"
  "_build/install/default/lib/Builder/builder.cmi"
  "_build/install/default/lib/Builder/builder.cmt"
  "_build/install/default/lib/Builder/builder.cmti"
  "_build/install/default/lib/Builder/builder.cmx"
  "_build/install/default/lib/Builder/builder.cmxa"
  "_build/install/default/lib/Builder/builder.ml"
  "_build/install/default/lib/Builder/builder.mli"
  "_build/install/default/lib/Builder/dune-package"
  "_build/install/default/lib/Builder/opam"
]
libexec: [
  "_build/install/default/lib/Builder/builder.cmxs"
]
doc: [
  "_build/install/default/doc/Builder/README.md"
]
